name: polyglot_cli
description: Generate l10n delegate from partition files.
version: 0.5.1
repository: https://github.com/karbunkul/polyglot_cli
topics:
  - polyglot
  - cli
  - language
  - intl
  - l10n

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.16.9

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  analyzer: ^6.4.1
  meta: ^1.15.0

dependencies:
  args: ^2.3.1
  basic_utils: ^5.4.0
  collection: ^1.17.0
  intl: ^0.19.0
  logging: ^1.1.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  prompts: ^2.0.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

executables:
  polyglot: polyglot_cli
