name: polyglot_cli
description: Generate l10n delegate from partition files.
version: 0.5.1
repository: https://github.com/karbunkul/polyglot_cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
dependencies:
  args: ^2.7.0
  basic_utils: ^5.8.2
  collection: ^1.19.1
  intl: ^0.20.2
  logging: ^1.1.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  prompts: ^2.0.0
  yaml: ^3.1.1
  yaml_writer: ^2.1.0

executables:
  polyglot: polyglot_cli
