name: polyglot_cli
description: Generate l10n delegate from partition files.
version: 0.5.0
repository: https://github.com/karbunkul/polyglot_cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
dependencies:
  args: ^2.3.1
  basic_utils: ^5.4.0
  collection: ^1.17.0
  intl: ^0.18.0
  logging: ^1.1.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  prompts: ^2.0.0
  yaml: ^3.1.2
  yaml_writer: ^1.0.2

executables:
  polyglot: polyglot_cli
